spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 851941661103-021vupdg1mupdtifoo0833p4pvltekd4.apps.googleusercontent.com
            client-secret: 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

server:
  forward-headers-strategy: native